defaults:
  - _self_
  - task@_global_: dmc/cheetah_run
  - override hydra/launcher: submitit_local

# Environment
frame_stack: 3
action_repeat: 2
# Agent
obs_shape: ???  # To be specified later
action_shape: ??? # To be specified later
feature_dim: 50
lr: 1e-4
discrete: ??? # To be specified later
# Replay
obs_spec: ??? # To be specified later
action_spec: ??? # To be specified later
nstep: 3
batch_size: 256
discount: 0.99
# Training
seed_steps: 2000
update_per_steps: 2
post_updates: 1000
# Evaluating
evaluate_per_steps: 5000
evaluate_episodes: 10
# Saving
save_session: false
save_path: ./Checkpoints/${Agent}_${experiment}/${environment.suite}/${task_name}_${seed}_Saved.pt
# Logging
log_video: false
log_tensorboard: false
# Plotting
plot: true
# Misc
device: cuda
alias_device: cpu
RL: true
# Experiment
Agent: Agents.DPGAgent
seed: 1
experiment: Exp

environment:
  _target_: Datasets.Environment.Environment
  task_name: ${task_name}
  frame_stack: ${frame_stack}
  action_repeat: ${action_repeat}
  max_episode_frames: null
  truncate_episode_frames: 1000
  seed: ${seed}
  suite: ${suite}
  batch_size: ${batch_size}
  num_workers: ${replay.num_workers}

agent:
  _target_: ${Agent}
  obs_shape: ${obs_shape}
  action_shape: ${action_shape}
  feature_dim: ${feature_dim}
  hidden_dim: 1024
  explore_steps: 2000
  stddev_schedule: ${stddev_schedule} # Specified in task/100K,500K,etc.
  stddev_clip: 0.3
  lr: ${lr}
  target_tau: 0.01
  discrete: ${discrete}
  RL: ${RL}
  device: ${device}
  log: ${log_tensorboard}

replay:
  _target_: Datasets.ExperienceReplay.ExperienceReplay
  path: ./Datasets/ReplayBuffer/${Agent}_${experiment}/${environment.suite}/${task_name}_${seed}_Memories
  obs_spec: ${obs_spec}
  action_spec: ${action_spec}
  capacity: 1000000
  batch_size: ${batch_size}
  num_workers: 4
  nstep: ${nstep}
  discount: ${discount}
  save: false

logger:
  _target_: Logger.Logger
  path: ./Benchmarking/${Agent}_${experiment}/${environment.suite}/
  task: ${task_name}
  seed: ${seed}

vlogger:
  _target_: Vlogger.Vlogger
  path: ./Benchmarking/${Agent}_${experiment}/${environment.suite}/${task_name}_${seed}_Video
  fps: 20

plotting:
  _target_: Plot.plot
  path: ./Benchmarking/${Agent}_${experiment}/${environment.suite}/${task_name}_${seed}_Plot.png
  experiments: ${experiment}
  suites: null
  tasks: null
  agents: null

hydra:
  run:
    dir: ./
  sweep:
    dir: ./
    subdir: ./
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./
